# Generated by Django 3.0.6 on 2020-06-07 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_auto_20200607_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='apartment_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartments.ApartmentType', verbose_name='тип'),
        ),
    ]
