# Generated by Django 3.0.6 on 2020-06-08 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_auto_20200607_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartments',
            options={'verbose_name': 'apartment', 'verbose_name_plural': 'apartments'},
        ),
        migrations.AlterField(
            model_name='apartments',
            name='apartment_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartments.ApartmentType'),
        ),
        migrations.AlterField(
            model_name='apartmenttype',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
